### ISSUE TITLE
TypedArray Unavailable (Go 1.13)

### ISSUE THREAD

**Issue by rshaalan** [gowebapi/webapi#5]
Error trying to build using Go v1.13:

"/go/src/github.com/gowebapi/webapi/core/js/js_js.go:56:19: undefined: js.TypedArray"

I commented out the references to this type in your code to get it building. Is that appropriate?

**Comment by martin-juhlin** [comment]
That is the quick fix. I have been stuck with an api refactoring and have not really started with 1.13 yet. Will try to fix this during next week.

**Comment by martin-juhlin** [comment]
the code compiles now under go 1.13
